### ISSUE TITLE
Hz

### ISSUE THREAD

**Issue by gyc521zsc** [Helicopt/fast-py-MOTMetrics#1]
Hello,I have a question I would like to ask you, how to calculate Hz.
![image](https://user-images.githubusercontent.com/50411057/67769256-14ef3880-fa8f-11e9-8a8a-93092ef223dc.png)

runtime?

**Comment by Helicopt** [comment]
Hello, thanks for raising the first issue. 

In MOT challenge, participants are required to calculate the speed of their own algorithms. However, there is not any relevant parts about estimating speed in the metrics tool, that means people need to calculate by themselves, maybe estimate it when running the algorithm.

Hope this helps.
